/*
 * File: TestInfoRenderer.java
 * Author: Fredrik Johansson
 * Date: 2016-10-31
 */

import javax.swing.*;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import java.awt.*;


/**
 * Specifies how a TestInfo object should be rendered in the GUI
 */
public class TestInfoRenderer implements ListCellRenderer<TestInfo> {

    /**
     * Will render a TestInfo as a colored text to a JList.
     * @param list List to render to
     * @param value TestInfo used to render
     * @param index Index in list
     * @param isSelected If selected
     * @param cellHasFocus If has focus
     * @return The rendered component to put in list
     */
    @Override
    public Component getListCellRendererComponent(JList<? extends TestInfo> list
                                                , TestInfo value,
                                                  int index,
                                                  boolean isSelected,
                                                  boolean cellHasFocus) {
        JTextPane pane = new JTextPane();
        pane.setBackground(UI.TRANSPARENT);
        pane.setForeground(UI.COLOR_TEXT);
        pane.setBorder(BorderFactory.createLineBorder(UI.TRANSPARENT, 6));
        StyledDocument text = pane.getStyledDocument();

        try {
            printIcon(value.getStatus(), text);
            printText(value, text);

        } catch (BadLocationException e) {
            // Thrown when text insert below 0 or above length of text and
            // should never happen as each insertString is in the end of text
            // Still ugly code to not ignore exception
        }
        return pane;
    }

    /**
     * Insert an icon based on test status
     * @param status Status of test
     * @param text Text to insert into
     * @throws BadLocationException If inserting text below 0 or above length of
     *                              text, which it should never do
     */
    private void printIcon(TestInfo.Status status, StyledDocument text)
                                            throws BadLocationException {

        Style textColor = text.addStyle("TextColor", null);
        switch (status) {
            case SUCCESS:
                StyleConstants.setForeground(textColor, UI.COLOR_SUCCESS);
                text.insertString(text.getLength(), " ✔ ", textColor);
                break;
            case FAILED:
                StyleConstants.setForeground(textColor, UI.COLOR_FAIL);
                text.insertString(text.getLength(), " ✘ ", textColor);
                break;
            case RUNNING:
                text.insertString(text.getLength(), " ↻ ", null);
                break;
            case WARNING:
                StyleConstants.setForeground(textColor, UI.COLOR_WARNING);
                text.insertString(text.getLength(), " ⚠ ", textColor);
                break;
        }
    }

    /**
     * Insert text.
     * @param value TestInfo to generate text based upon
     * @param text Text to add the new text onto
     * @throws BadLocationException If inserting text below 0 or above length of
     *                              text, which it should never do
     */
    private void printText(TestInfo value, StyledDocument text)
                                            throws BadLocationException {

        text.insertString(text.getLength(), value.getName(), null);
        if (value.hasException()) {
            Style textColor = text.addStyle("TextColor", null);
            text.insertString(text.getLength(), "\n    Generated by ", null);
            StyleConstants.setForeground(textColor, UI.COLOR_FAIL);
            text.insertString(text.getLength(),
                    value.getException().getClass().getName(), textColor);
        }

        if (value.getStatus() == TestInfo.Status.RUNNING) {
            text.insertString(text.getLength(), ": Running", null);
        }
    }
}
